/** @type {import("eslint").Linter.Config[]} */
export default [
  {
    files: ["js/**/*.js", "js/**/*.json"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser built-ins
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        console: "readonly",
        performance: "readonly",
        Blob: "readonly",
        URL: "readonly",
        atob: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        structuredClone: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        fetch: "readonly",
        FileReader: "readonly",
        FileReaderSync: "readonly",
        FileReaderWriter: "readonly",
        // Third-party libs
        gsap: "readonly",
        jQuery: "readonly",
        $: "readonly",
        PIXI: "readonly",
        ExcelJS: "readonly",
        // Cross-file data globals
        ABILITIES_DB: "readonly",
        ANCESTRY_MAP: "readonly",
        ARTISAN_SKILLS: "readonly",
        BASE_SKILL_POINTS: "readonly",
        BREAKTHROUGH_DATA: "readonly",
        BREAKTHROUGH_SKILL_BONUSES: "readonly",
        CLASS_ABILITIES_DATA: "readonly",
        CLASS_DATA: "readonly",
        CLASS_INDEX: "readonly",
        CLASS_SKILL_DATA: "readonly",
        CRAFTING_GATHERING_SKILLS: "readonly",
        DEFAULT_CLASS_SKILLS: "readonly",
        EXPERTISE_MULTIPLIER: "readonly",
        ITEMS_DATA: "readonly",
        KEYWORDS_DB: "readonly",
        MAIN_STATS: "readonly",
        MAIN_STATS_ARRAY: "readonly",
        MIRANE_TEMPLATE_B64: "readonly",
        RACE_DATA: "readonly",
        RACE_SKILL_DATA: "readonly",
        SKILL_CAP: "readonly",
        SKILL_EXPERTISE_EXAMPLES: "readonly",
        SKILL_GRANTING_BREAKTHROUGHS: "readonly",
        SKILL_GROUPS: "readonly",
        SUB_STATS: "readonly",
        SUB_STATS_ARRAY: "readonly",
        TRAIT_DESCRIPTIONS: "readonly",
        // Cross-file scene globals
        BackgroundScene: "readonly",
        BreakthroughScene: "readonly",
        ClassSelectScene: "readonly",
        EquipmentScene: "readonly",
        RaceSelectScene: "readonly",
        SkillsStepScene: "readonly",
        StatsScene: "readonly",
        SummaryScene: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-console": "off",
    },
  },
];
